# -*- coding: utf-8 -*-
"""Definitions for the API application."""

# HTTP status code
HTTP_STATUS_CODE_OK = 200
HTTP_STATUS_CODE_CREATED = 201
HTTP_STATUS_CODE_NO_CONTENT = 204
HTTP_STATUS_CODE_REDIRECT = 302
HTTP_STATUS_CODE_BAD_REQUEST = 400
HTTP_STATUS_CODE_UNAUTHORIZED = 401
HTTP_STATUS_CODE_FORBIDDEN = 403
HTTP_STATUS_CODE_NOT_FOUND = 404
HTTP_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE = 415
HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR = 500
